# Generated by Django 6.0.5 on 2026-05-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cake', 'Tortas'), ('cupcake', 'Cupcakes'), ('coffee', 'Cafetería'), ('dessert', 'Postres'), ('drink', 'Bebidas'), ('other', 'Otros')], max_length=50),
        ),
    ]
