# Generated by Django 6.0.5 on 2026-05-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_active_product_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='olaclick_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cake', 'Tortas'), ('cupcake', 'Cupcakes'), ('coffee', 'Cafetería'), ('dessert', 'Postres'), ('drink', 'Bebidas'), ('waffle', 'Waffles'), ('icecream', 'Helados'), ('frappe', 'Frappes'), ('promo', 'Promociones'), ('other', 'Otros')], default='other', max_length=50),
        ),
    ]
